/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import entities.Adocao;
import entities.Animal;
import entities.Cachorro;
import entities.Gato;
import entities.Tutor;
import javax.swing.JOptionPane;

/**
 *
 * @author aluno
 */
public class TelaRegistroAdocao extends javax.swing.JFrame {

    /**
     * Creates new form TelaInicial
     */
    public TelaRegistroAdocao() {
        initComponents();
        var novoGato1 = new Gato("TESTE", 2, 6, "BRANCO");
        var novoGato2 = new Gato("Linda", 2, 6, "CINZA");
        var novoGato3 = new Gato("Gatinha", 2, 6, "BRANCO");
        var novoCachorro1 = new Cachorro("Princesa", 20, 80, "CARAMELO");
        var novoCachorro2 = new Cachorro("Princesa", 20, 80, "BRANCO");
        var novoCachorro3 = new Cachorro("Negao", 20, 80, "PRETO");
        
        novoGato1.cacadastrarAnimal();
        novoGato2.cacadastrarAnimal();
        novoGato3.cacadastrarAnimal();
        
        novoCachorro1.cacadastrarAnimal();
        novoCachorro2.cacadastrarAnimal();
        novoCachorro3.cacadastrarAnimal();
        
        Tutor.cadastrarTutor("Yngred", "Soares", "717171", 20);
        Tutor.cadastrarTutor("Mauri", "Volpato", "88956", 23);
        Tutor.cadastrarTutor("Jeremias", "", "", 60);   

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnArquivarTutor1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        txtBuscarTutorPorNome = new javax.swing.JTextField();
        btnEncerrarSessao = new javax.swing.JButton();
        btnRetornar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnBuscarTutor = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtBuscarPetPorNome = new javax.swing.JTextField();
        btnBuscarPet = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtListaDeAnimais = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        comboBoxEspecie = new javax.swing.JComboBox<>();
        comboBoxSexo = new javax.swing.JComboBox<>();
        btnRegistrarAdocao = new javax.swing.JButton();

        btnArquivarTutor1.setText("RETORNAR");
        btnArquivarTutor1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnArquivarTutor1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(102, 0, 51));

        txtBuscarTutorPorNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarTutorPorNomeActionPerformed(evt);
            }
        });

        btnEncerrarSessao.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnEncerrarSessao.setText("X");
        btnEncerrarSessao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEncerrarSessaoActionPerformed(evt);
            }
        });

        btnRetornar.setText("RETORNAR");
        btnRetornar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetornarActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Siemens Serif", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("REGISTRO ADOÇÃO");

        jLabel3.setFont(new java.awt.Font("Siemens Serif", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("DEFINA O TUTOR QUE ESTA ADOTANDO");

        btnBuscarTutor.setText("BUSCAR TUTOR");
        btnBuscarTutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarTutorActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Siemens Serif", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("ESCOLHA O ANIMAL");

        txtBuscarPetPorNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarPetPorNomeActionPerformed(evt);
            }
        });

        btnBuscarPet.setText("SELECIONAR PET");
        btnBuscarPet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarPetActionPerformed(evt);
            }
        });

        txtListaDeAnimais.setColumns(20);
        txtListaDeAnimais.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtListaDeAnimais.setRows(5);
        jScrollPane1.setViewportView(txtListaDeAnimais);

        jLabel5.setFont(new java.awt.Font("Siemens Serif", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("ESPECIE");

        comboBoxEspecie.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TODOS", "GATOS", "CACHORROS" }));
        comboBoxEspecie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxEspecieActionPerformed(evt);
            }
        });

        comboBoxSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TODOS", "MACHOS", "FEMEAS" }));
        comboBoxSexo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxSexoActionPerformed(evt);
            }
        });

        btnRegistrarAdocao.setText("REGISTRAR ADOCAO");
        btnRegistrarAdocao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarAdocaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(btnRetornar, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 641, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                        .addComponent(btnEncerrarSessao, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(txtBuscarTutorPorNome, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnBuscarTutor, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                                .addComponent(btnRegistrarAdocao, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(comboBoxEspecie, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(comboBoxSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtBuscarPetPorNome, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnBuscarPet, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEncerrarSessao, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnRetornar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBuscarTutorPorNome, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarTutor, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRegistrarAdocao, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBuscarPetPorNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarPet)
                    .addComponent(comboBoxEspecie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboBoxSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnEncerrarSessaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEncerrarSessaoActionPerformed
        dispose();
    }//GEN-LAST:event_btnEncerrarSessaoActionPerformed

    private void btnArquivarTutor1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnArquivarTutor1ActionPerformed
        TelaInicial tela = new TelaInicial();
        this.dispose();
        tela.setVisible(true);
    }//GEN-LAST:event_btnArquivarTutor1ActionPerformed

    private void btnRetornarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetornarActionPerformed
        TelaInicial tela = new TelaInicial();
        this.dispose();
        tela.setVisible(true);
    }//GEN-LAST:event_btnRetornarActionPerformed

    private void txtBuscarTutorPorNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarTutorPorNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarTutorPorNomeActionPerformed

    private void btnBuscarTutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarTutorActionPerformed
        
    }//GEN-LAST:event_btnBuscarTutorActionPerformed

    private void txtBuscarPetPorNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarPetPorNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarPetPorNomeActionPerformed

    private void btnBuscarPetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarPetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarPetActionPerformed

    private void comboBoxEspecieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxEspecieActionPerformed
       int indexEspecie = comboBoxEspecie.getSelectedIndex();
       switch(indexEspecie){
           case 0:               
               txtListaDeAnimais.setText(Animal.listarAnimais());
               break;
           case 1:
               txtListaDeAnimais.setText(Animal.listarAnimaisPorEspecie("GATO"));
               break;
           case 2: 
               txtListaDeAnimais.setText(Animal.listarAnimaisPorEspecie("CACHORRO"));
               break;
       }
    }//GEN-LAST:event_comboBoxEspecieActionPerformed

    private void comboBoxSexoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxSexoActionPerformed
         int indexSexo = comboBoxSexo.getSelectedIndex();
         String resultado = txtListaDeAnimais.getText();
         switch(indexSexo){
             case 0: 
                 txtListaDeAnimais.setText(resultado + " TODOS");
                 break;
             case 1:
                 txtListaDeAnimais.setText(resultado + " MACHOS");
                 break;
             case 2:
                 txtListaDeAnimais.setText(resultado + " FEMEAS");
                 break;
         }
    }//GEN-LAST:event_comboBoxSexoActionPerformed

    private void btnRegistrarAdocaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarAdocaoActionPerformed
        String nomeTutor = txtBuscarTutorPorNome.getText();
        var tutor = Tutor.buscarTutorPorNome(nomeTutor);
        String nomePet = txtBuscarPetPorNome.getText();
        var animal = Animal.buscarPorNome(nomePet);
       
        if(tutor!=null && animal != null){
            Adocao.registrarAdocao(tutor, animal);
            System.out.println("Animal adotado: "+animal.getNome());
            JOptionPane.showMessageDialog(null, "Adocao cadastrada com sucesso!\n "
                + animal.getNome() + " foi adotado por "+ tutor.getNome()+".");
            txtBuscarTutorPorNome.setText("");
            txtBuscarPetPorNome.setText("");    
        }
        else {
            JOptionPane.showMessageDialog(null, "TODOS OS CAMPOS DEVEM SER PREENCHIDOS!");
        }       
    }//GEN-LAST:event_btnRegistrarAdocaoActionPerformed


    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaRegistroAdocao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaRegistroAdocao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaRegistroAdocao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaRegistroAdocao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //<txtBuscarTutorPorNome/editor-fold>
        //</editor-fold>
        //</editor-fold>

        /*btnRegistrarAdocao Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaRegistroAdocao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnArquivarTutor1;
    private javax.swing.JButton btnBuscarPet;
    private javax.swing.JButton btnBuscarTutor;
    private javax.swing.JButton btnEncerrarSessao;
    private javax.swing.JButton btnRegistrarAdocao;
    private javax.swing.JButton btnRetornar;
    private javax.swing.JComboBox<String> comboBoxEspecie;
    private javax.swing.JComboBox<String> comboBoxSexo;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtBuscarPetPorNome;
    private javax.swing.JTextField txtBuscarTutorPorNome;
    private javax.swing.JTextArea txtListaDeAnimais;
    // End of variables declaration//GEN-END:variables
}
